name: ELD_CanonEOS70D
manual_seed: 3407 # is all you need
output: runs

loss:
  types:
  - L1
  weights:
  - 1.0

pretrained: /data/models/Carlos/RAWDenoising/runs/SONY/checkpoints/best_model.pth

data:
  name: ELDDataset
  datadir: /data/dataset/Carlos/ELD/
  camera: CanonEOS70D
  num_workers: 16
  pin_memory: true
  argument:
    transpose: true
    h_flip: true
    v_flip: true
  train:
    batch_size: 1
    pairs_file_path: CanonEOS70D_Finetune.txt #24
    patch_size: 512
  test:
    batch_size: 1
    pairs_file_path: CanonEOS70D_WO_Finetune.txt #96

model:
  name: MetaRawFormer
  MetaRawFormer:
    in_channels: 4
    out_channels: 4
    dim: 32
    layers: 4
    num_meta_keys: 4
    meta_dims: 32
    num_blocks: [2,2,2,2]
    num_refinement_blocks: 2
    heads: [1, 2, 4, 8]

train:
  base_lr: 5.0e-5
  last_lr_epoch: 20
  clip_grad: 0.1
  epochs: 20
  lr_scheduler:
    type: cosine
  optimizer: 
    type: adamw
    eps: 1.0e-8
    betas: [0.9, 0.999]
  min_lr: 5.0e-5
  weight_decay: 0
  warmup_epochs: 0

test:
  merge_test: true
  num_patch: 4 #null, -1, 2, 4
  patch_size: null